export const ACTIVITY_EVENT_TYPES = [
  "organization.created",
  "organization.updated",
  "project.created",
  "project.updated",
  "project.member_joined",
  "project.member_invited",
  "project.member_role_changed",
  "project.member_removed",
  "task.created",
  "task.updated",
  "task.status_changed",
  "task.completed",
  "task.assigned",
  "task.deleted",
  "task.attachment_added",
  "task.attachment_removed",
  "issue.created",
  "issue.updated",
  "issue.status_changed",
  "issue.closed",
  "issue.deleted",
  "comment.created",
  "comment.deleted",
] as const;

export const ACTIVITY_EVENT_LABELS: Record<string, string> = {
  "organization.created": "Organization created",
  "organization.updated": "Organization updated",
  "project.created": "Project created",
  "project.updated": "Project updated",
  "project.member_joined": "Member joined",
  "project.member_invited": "Member invited",
  "project.member_role_changed": "Member role changed",
  "project.member_removed": "Member removed",
  "task.created": "Task created",
  "task.updated": "Task updated",
  "task.status_changed": "Task status changed",
  "task.completed": "Task completed",
  "task.assigned": "Task assigned",
  "task.deleted": "Task deleted",
  "task.attachment_added": "Attachment added",
  "task.attachment_removed": "Attachment removed",
  "issue.created": "Issue opened",
  "issue.updated": "Issue updated",
  "issue.status_changed": "Issue status changed",
  "issue.closed": "Issue closed",
  "issue.deleted": "Issue deleted",
  "comment.created": "Comment added",
  "comment.deleted": "Comment deleted",
};
